name: Build and Deploy Demo
on:
  push:
    branches:
      - master
      - feature/async-fix
jobs:
  build-and-deploy-demo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Build
      run: yarn prep && yarn build && yarn lint-demo && yarn build-demo
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./packages/dendriform-demo/out
