name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn prep --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true
      
      - name: Build demo
        run: yarn build-demo
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          CI: true

      - name: Size
        run: yarn size
        env:
          CI: true
